Update update_azure_public_ip_ranges.yml

diff --git a/.github/workflows/update_azure_public_ip_ranges.yml b/.github/workflows/update_azure_public_ip_ranges.yml
--- a/.github/workflows/update_azure_public_ip_ranges.yml
+++ b/.github/workflows/update_azure_public_ip_ranges.yml
@@ -27,7 +27,7 @@ jobs:
           fi
           
           wget -O $(basename "$SERVICE_TAGS_URL") "$SERVICE_TAGS_URL" || { echo "Failed to download file"; exit 1; }
-          cp -i $(basename "$SERVICE_TAGS_URL") latest.json || { echo "Failed to copy file"; exit 1; }
+          /bin/cp -i $(basename "$SERVICE_TAGS_URL") latest.json || { echo "Failed to copy file"; exit 1; }
           
           echo "Operation completed successfully."
       - name: Commit IP Ranges
