Update update_azure_ip_ranges.yml

diff --git a/.github/workflows/update_azure_ip_ranges.yml b/.github/workflows/update_azure_ip_ranges.yml
--- a/.github/workflows/update_azure_ip_ranges.yml
+++ b/.github/workflows/update_azure_ip_ranges.yml
@@ -22,8 +22,8 @@ jobs:
               echo "No URL found. Exiting."
               exit 1
           fi
-          wget $SERVICE_TAGS_URL || { echo "Failed to download file"; exit 1; }
-          cp -i $(basename $SERVICE_TAGS_URL) ServiceTags_Public_Latest.json || { echo "Failed to copy file"; exit 1; }
+          wget -O $(basename "$SERVICE_TAGS_URL") "$SERVICE_TAGS_URL" || { echo "Failed to download file"; exit 1; }
+          cp -i $(basename "$SERVICE_TAGS_URL") ServiceTags_Public_Latest.json || { echo "Failed to copy file"; exit 1; }
           echo "Operation completed successfully."
       - name: Commit Azure IP Ranges
         run: |
