Update update_azure_ip_ranges.yml

diff --git a/.github/workflows/update_azure_ip_ranges.yml b/.github/workflows/update_azure_ip_ranges.yml
--- a/.github/workflows/update_azure_ip_ranges.yml
+++ b/.github/workflows/update_azure_ip_ranges.yml
@@ -1,5 +1,3 @@
-# This is a basic workflow to help you get started with Actions
-
 name: Update Azure IP Ranges
 
 on: 
@@ -7,7 +5,6 @@ on:
   schedule:
     - cron: "0 0 * * *"
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   update_ip_ranges:
     runs-on: ubuntu-latest
@@ -16,13 +13,18 @@ jobs:
       # https://stackoverflow.com/a/53939113
       - name: Download Azure IP Ranges
         run: |
-          BASE_DIR=ranges/azure/
-          mkdir -p $BASE_DIR
-          cd $BASE_DIR
+          BASE_DIR="ranges/azure/"
+          mkdir -p "$BASE_DIR" || { echo "Failed to create base directory"; exit 1; }
+          cd "$BASE_DIR" || { echo "Failed to change directory to $BASE_DIR"; exit 1; }
           MS_IP_RANGES_URL="https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519"
-          SERVICE_TAGS_URL=$(curl -Lfs "${MS_IP_RANGES_URL}" | grep -Eo 'href="https?://download.microsoft.com/download/[^"]+"' | grep -m1 -Eo '(http|https)://[^"]+')
-          wget $SERVICE_TAGS_URL
-          cp -i $(basename $SERVICE_TAGS_URL) ServiceTags_Public_Latest.json
+          SERVICE_TAGS_URL=$(curl -Lfs "${MS_IP_RANGES_URL}" | grep -Eo 'href="https?://download.microsoft.com/download/[^"]+"' | grep -m1 -Eo '(http|https)://[^"]+')  || { echo "Failed to extract URL"; exit 1; }
+          if [[ -z "$SERVICE_TAGS_URL" ]]; then
+              echo "No URL found. Exiting."
+              exit 1
+          fi
+          wget $SERVICE_TAGS_URL || { echo "Failed to download file"; exit 1; }
+          cp -i $(basename $SERVICE_TAGS_URL) ServiceTags_Public_Latest.json || { echo "Failed to copy file"; exit 1; }
+          echo "Operation completed successfully."
       - name: Commit Azure IP Ranges
         run: |
           git config --global user.name 'Stig Voss'
